name: Run the qodo-cover action (Typescript)

on:
  workflow_dispatch:
    inputs:
      desired_coverage:
        description: "Desired coverage percentage"
        required: false
        default: "70"

permissions:
  pull-requests: write
  contents: write

jobs:
  run-qodo-cover-ts:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Qodo Cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover@v0.1.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_language: typescript
          project_root: .
          code_coverage_report_path: coverage/cobertura-coverage.xml
          test_command: "npm run test"
          model: gpt-4
          desired_coverage: ${{ github.event.inputs.desired_coverage }}
          test_folder: src/test
          source_folder: src
          branch: ${{ github.ref_name }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
